CREATE DATABASE IF NOT EXISTS NAVIGATOR;

USE NAVIGATOR;

CREATE TABLE NAVIGATOR.T_APP_INF
(
    APP_ID     VARCHAR(16)  NOT NULL PRIMARY KEY COMMENT '应用ID',
    APP_KEY    VARCHAR(32)  NOT NULL DEFAULT '' COMMENT '应用KEY',
    APP_NAME   VARCHAR(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    DEPARTMENT VARCHAR(20)  NOT NULL DEFAULT '' COMMENT '部门',
    OWNER      VARCHAR(16)  NOT NULL DEFAULT '' COMMENT '应用所有人',
    STATUS     INT          NOT NULL DEFAULT 0 COMMENT '状态',
    MEMO       VARCHAR(255) COMMENT '备注',
    CREATED_AT TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建日期',
    CREATED_BY VARCHAR(32)  NOT NULL COMMENT '创建人',
    UPDATED_AT TIMESTAMP COMMENT '最后更新时间',
    UPDATED_BY VARCHAR(32)  NOT NULL COMMENT '最后更新人'
) CHARSET = UTF8MB4 COMMENT '应用信息表';

CREATE UNIQUE INDEX I_APP_ID_INDEX ON NAVIGATOR.T_APP_INF (APP_ID);

CREATE TABLE NAVIGATOR.T_APP_CONFIG
(
    APP_ID     VARCHAR(16) NOT NULL COMMENT '应用ID',
    CLUSTER    VARCHAR(20) NOT NULL DEFAULT '' COMMENT '集群名称',
    PROFILE    VARCHAR(19) NOT NULL DEFAULT '' COMMENT '环境',
    CONFIG     Text NOT NULL COMMENT '配置（文件）',
    VERSION    VARCHAR(18) NOT NULL DEFAULT '' COMMENT '版本号',
    STATUS     INT         NOT NULL DEFAULT 0 COMMENT '状态',
    MEMO       VARCHAR(255) COMMENT '备注',
    CREATED_AT TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建日期',
    CREATED_BY VARCHAR(32) NOT NULL COMMENT '创建人',
    UPDATED_AT TIMESTAMP COMMENT '最后更新时间',
    UPDATED_BY VARCHAR(32) NOT NULL COMMENT '最后更新人'
) CHARSET = UTF8MB4 COMMENT '应用配置表';

CREATE INDEX I_APP_CONFIG_ID_INDEX ON NAVIGATOR.T_APP_CONFIG (APP_ID);
CREATE INDEX I_APP_CONFIG_QUERY_INDEX ON NAVIGATOR.T_APP_CONFIG (APP_ID, CLUSTER, PROFILE);


