# DROP DATABASE  NAVIGATOR;

CREATE DATABASE IF NOT EXISTS NAVIGATOR;

USE NAVIGATOR;

CREATE TABLE NAVIGATOR.T_APP_INF
(
    APP_ID     VARCHAR(16)  NOT NULL PRIMARY KEY COMMENT '应用ID',
    APP_KEY    VARCHAR(32)  NOT NULL DEFAULT '' COMMENT '应用KEY',
    APP_NAME   VARCHAR(255) NOT NULL DEFAULT '' COMMENT '应用名称',
    DEPARTMENT VARCHAR(20)  NOT NULL DEFAULT '' COMMENT '部门',
    OWNER      VARCHAR(16)  NOT NULL DEFAULT '' COMMENT '应用所有人',
    STATUS     INT          NOT NULL DEFAULT 0 COMMENT '状态(1启用/0未启用)',
    MEMO       VARCHAR(255) COMMENT '备注',
    CREATED_AT TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    CREATED_BY VARCHAR(32)  NOT NULL COMMENT '创建人',
    UPDATED_AT TIMESTAMP COMMENT '更新时间',
    UPDATED_BY VARCHAR(32)  NOT NULL COMMENT '更新人'
) CHARSET = UTF8MB4 COMMENT '应用信息表';

CREATE UNIQUE INDEX I_APP_ID_INDEX ON NAVIGATOR.T_APP_INF (APP_ID);


CREATE TABLE NAVIGATOR.T_APP_PROFILE
(
    APP_ID     VARCHAR(16)  NOT NULL COMMENT '应用ID',
    CLUSTER    VARCHAR(20)  NOT NULL DEFAULT '' COMMENT '集群名称',
    PROFILE    VARCHAR(19)  NOT NULL DEFAULT '' COMMENT '环境',
    NOTIFY_URL VARCHAR(100) NOT NULL COMMENT '通知URL',
    CID        VARCHAR(16)  NOT NULL COMMENT '配置标识',
    STATUS     INT          NOT NULL DEFAULT 0 COMMENT '状态(1启用/0未启用)',
    MEMO       VARCHAR(255) COMMENT '备注',
    CREATED_AT TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    CREATED_BY VARCHAR(32)  NOT NULL COMMENT '创建人',
    UPDATED_AT TIMESTAMP COMMENT '更新时间',
    UPDATED_BY VARCHAR(32)  NOT NULL COMMENT '更新人'
) CHARSET = UTF8MB4 COMMENT '应用环境表';

CREATE INDEX I_APP_PROFILE_ID_INDEX ON NAVIGATOR.T_APP_PROFILE (APP_ID);
CREATE UNIQUE INDEX I_APP_PROFILE_QUERY_INDEX ON NAVIGATOR.T_APP_PROFILE (APP_ID, CLUSTER, PROFILE);

CREATE TABLE NAVIGATOR.T_APP_CONFIG
(
    CID        VARCHAR(16) NOT NULL COMMENT '配置标识',
    CONFIG     Text        NOT NULL COMMENT '配置（文件）',
    STATUS     INT         NOT NULL DEFAULT 0 COMMENT '状态(1正式/0未启用)',
    MEMO       VARCHAR(255) COMMENT '备注',
    CREATED_AT TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    CREATED_BY VARCHAR(32) NOT NULL COMMENT '创建人',
    UPDATED_AT TIMESTAMP COMMENT '更新时间',
    UPDATED_BY VARCHAR(32) NOT NULL COMMENT '更新人'
) CHARSET = UTF8MB4 COMMENT '应用配置表';

CREATE INDEX I_APP_CONFIG_ID_INDEX ON NAVIGATOR.T_APP_CONFIG (CID);
CREATE UNIQUE INDEX I_APP_CONFIG_QUERY_INDEX ON NAVIGATOR.T_APP_CONFIG (CID, STATUS, CREATED_AT);


